# Generated by Django 4.2.7 on 2023-11-19 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('inicio_inscricao', models.DateField()),
                ('fim_inscricao', models.DateField()),
                ('data_largada', models.DateField()),
                ('hora_largada', models.TimeField()),
                ('percurso', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('site', models.CharField(max_length=150)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cidade')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizador')),
            ],
        ),
        migrations.CreateModel(
            name='ContatoOrganizador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=100)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('tipo_contato', models.CharField(choices=[('Celular', 'Celular'), ('Fixo', 'Fixo'), ('Email', 'Email')], max_length=10)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizador')),
            ],
        ),
        migrations.CreateModel(
            name='ContatoAtleta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=100)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('tipo_contato', models.CharField(choices=[('Celular', 'Celular'), ('Fixo', 'Fixo'), ('Email', 'Email')], max_length=10)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.atleta')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cidade'),
        ),
    ]
